### ISSUE TITLE
Progress semicircle is not displayed correctly in Internet Explorer

### ISSUE THREAD

**Issue by stianfredriksen** [ThomasBem/react-progressbar-semicircle#7]
The Progressbar semicircle is not displayed as intended in Internet explorer. See attached image. 

![ie](https://user-images.githubusercontent.com/24889654/38273494-6186e6c4-378c-11e8-830e-3c72b03aa49e.JPG)

This also appliesfor Microsoft Edge, where the progress from right instead of left.
![edge](https://user-images.githubusercontent.com/24889654/38273564-8f9abc02-378c-11e8-9ec0-81d7dc8fe62f.JPG)

**Comment by ThomasBem** [comment]
Thanks for the support on this one! Your fix also added support for Safari 👍
